### PR TITLE
first release

### PR DESCRIPTION
**Pull request by jdhoffa**
- Increment version number to 0.0.2
- align NEWS content

### CODE REVIEW

**Review by cjyetman — APPROVED** [review]
ok, so now it's clear to me that there is not an intention to have these versions aligned across the various repos?

**Comment by jdhoffa** [comment]
> ok, so now it's clear to me that there is not an intention to have these versions aligned across the various repos?

Yes, it is not. Each package will be versioned on it's own. Some packages may not require any changes or updates between releases, and so we shouldn't just arbitrarily release them if there is no difference.

**Comment by cjyetman** [comment]
Was there not an intention to "tag", not "release", all relevant repos with a common tag for a given release so that it's easy to reconstruct?

**Comment by jdhoffa** [comment]
> Was there not an intention to "tag", not "release", all relevant repos with a common tag for a given release so that it's easy to reconstruct?

Hmm, no that wasn't necessarily my intent! I think it's ok if each repo has a different tag:
E.g. PACTA GENERAL Release 06.06.23 could depend on:
pacta.portfolio.allocate v0.0.1
pacta.interactive.report v0.4.0
etc.

One of the goals was to just be able to point to the latest release of each package, and indicate that the latest release corresponds to what is on GENERAL (whatever the number)

But i think it's sort of more confusing to arbitrarily try to link up the versions of all the packages? 

Like if we do another release to GENERAL for 2022Q4, and none of the packages change at all, it seems odd to bump their version number.

**Comment by cjyetman** [comment]
I get that, but I'm talking about "tags" not "releases" or "version numbers". "tags" can point to any commit, and more than one tag can point to the same commit. So I was imagining we could "tag", not version/release, each repo with a common tag when a new build is made so that it's easy to go to each repo and say "this is the commit where that build was made with", and a tag for 2021Q4_2023.06.05 could point to the same commit as a tag for 2022Q4_2023.06.23

**Comment by jdhoffa** [comment]
> I get that, but I'm talking about "tags" not "releases" or "version numbers". "tags" can point to any commit, and more than one tag can point to the same commit. So I was imagining we could "tag", not version/release, each repo with a common tag when a new build is made so that it's easy to go to each repo and say "this is the commit where that build was made with", and a tag for 2021Q4_2023.06.05 could point to the same commit as a tag for 2022Q4_2023.06.23

Hmm, that is a very good idea. I back it

**Pull request merged**
